name: Data Refresh Dev

on: [push]
  #schedule:
   # - cron:  '0 */4 * * *'
jobs:
  data_refresh_dev:
    name: coronavirus dataset refresh
    runs-on: ubuntu-18.04 
    container: 
     image: rkrispin/coronavirus:dev
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with: 
          ref: 'dev'
      - name: Refresh the data
        run: Rscript ./data_raw/data_refresh.R
      - name: Push the updates
        if: success()
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
              git init
              git config --global user.name 'RamiKrispin'
              git config --global user.email 'ramkrisp@umich.edu'
              git add data/*
              git add csv/*
              git commit -m 'coronavirus dataset autoup date [dev]'
              git push origin dev
          fi
