name: Data Refresh

on: [push]
  #schedule:
   # - cron:  '0 */4 * * *'
jobs:
  data_refresh_dev:
    name: coronavirus dataset refresh
    runs-on: ubuntu-18.04 
    container: 
     image: rkrispin/coronavirus:dev
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 'dev'
          token: ${{ github.token }}
          clean: 'true'
          fetch-depth: '1'
      - name: Refresh the data
        run: Rscript ./data_raw/data_refresh.R
      - name: Push the updates
        if: success()
        run: |
              git init
              git config --global user.name 'RamiKrispin'
              git config --global user.email 'ramkrisp@umich.edu'
              git commit -am 'coronavirus dataset autoup date [dev]'
